<?php

namespace Vendor\Package\Tests;

// @todo fill code after
use PHPUnit\Framework\TestCase;

final class SomeTest extends TestCase
{
    public function test()
    {
        $someMock = $this->createMock(SomeRepository::class);
    }
}
?>
-----
<?php

namespace Vendor\Package\Tests;

// @todo fill code after
use PHPUnit\Framework\TestCase;

final class SomeTest extends TestCase
{
    public function test()
    {
        $someMock = $this->createMock(SomeRepository::class);
    }
}
?>
